<?php

/**
 *
 * @author erasmussen
 *
 */
abstract class ReleaseMigration extends Migration {
  public function __construct() {
    parent::__construct(MigrateGroup::getInstance('release'));

    $this->team = array(
      new MigrateTeamMember('Eric Rasmussen', 'eric@unl.edu', t('M.M.F.')),
    );

    // Use another database
    Database::addConnectionInfo('news_migration', 'default', array(
      'driver' => 'mysql',
      'database' => 'news',
      'username' => 'root',
      'password' => 'ertyu9',
      'host' => 'localhost',
      'prefix' => '',
    ));

  }
}

/**
 *
 * @author erasmussen
 *
 */
class ReleaseNodeMigration extends ReleaseMigration {
  public function __construct() {
    parent::__construct();
    $this->description = t('Migrate release pages to nodes');

    $query = Database::getConnection('default', 'news_migration')
      ->select('releases', 'r')
      ->fields('r', array('id', 'headline', 'body',
                          'eventdate', 'eventtime', 'eventenddate', 'eventlocation',
                          'release_date', 'datecreated', 'datemodified', 'city'));

    $this->source = new MigrateSourceSQL($query);

    $this->destination = new MigrateDestinationNode('news_release');

    $this->map = new MigrateSQLMap($this->machineName,
      array(
        'id' => array(
          'type' => 'int',
          'length' => 11,
          'unsigned' => TRUE,
          'not null' => TRUE,
          'alias' => 'r',
        ),
      ),
      MigrateDestinationNode::getKeySchema()
    );

    // Fields
    $this->addFieldMapping('title', 'headline');
    $this->addFieldMapping('body', 'body')->arguments(array('format' => 'full_html'));
    $this->addFieldMapping('field_location', 'eventlocation');
    $this->addFieldMapping('field_date', 'eventdate');

    // Metadata
    $kelly = user_load_by_name('kbartling2');
    $this->addFieldMapping('uid')->defaultValue($kelly->uid);
    $this->addFieldMapping('created', 'datecreated');
    $this->addFieldMapping('changed', 'datemodified');
    $this->addFieldMapping('scheduler', 'release_date');
    $this->addFieldMapping('og_group_ref')->defaultValue(4);

     // Unmapped source fields
    $this->addUnmigratedSources(array('eventtime', 'eventenddate', 'city'));

    // Unmapped destination fields
    $this->addUnmigratedDestinations(array('sticky', 'is_new'));
  }

  /**
   * (non-PHPdoc)
   * @see Migration::prepareRow()
   */
  public function prepareRow($current_row) {
    // Format eventdate
    $date_data = array(
      'from' => (string) $current_row->eventdate . $current_row->eventtime,
      'to' => (string) $current_row->eventenddate,
    );
    $current_row->eventdate = drupal_json_encode($date_data);

    // Format release_date datetime field as timestamp for Scheduler
    $current_row->release_date = strtotime($current_row->release_date);
  }
}



/**
 * Scheduler support
 */
class MigrateSchedulerHandler extends MigrateDestinationHandler {
  public function __construct() {
    $this->registerTypes(array('node'));
  }

  public function fields($entity_type, $bundle) {
    return array(
      'scheduler' => t('Scheduler: Publishing date for scheduler'),
    );
  }

  public function complete($entity, stdClass $row) {
    db_insert('scheduler')
          ->fields(array(
            'nid' => $entity->nid,
            'publish_on' => $row->release_date,
            'unpublish_on' => 0,
          ))
          ->execute();
  }
}
